config/routes.rb
OpenMarket::Application.routes.draw do
  get "search/simple"

  get "search/advanced"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  #
  # Static pages
  #
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"

  #
  # Default routes
  #
  resources :items do
    resources :photos
  end
  resources :shops do
    resources :items do
      resources :photos
    end
  end
  resources :sessions

  #
  # Root
  #
  root :to => 'static_pages#home'

  #
  # Generic paths
  #
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/signup',  to: 'users#new'
  match '/search',  to: 'search#simple'
  match '/search/advanced',  to: 'search#advanced'
  match '/login',   to: 'sessions#new'
  match '/logout',  to: 'sessions#destroy'

  match '/users/:username/edit', to: 'users#edit'
  match '/users/:username', to: 'users#update', :via => :put
  match '/users/:username', to: redirect { |params, req| "/#{params[:username]}" }

  #
  # Paths for user scoped access
  #
  scope '/:username', :constraints => ProfileConstraint do
    get '' => 'users#show'
    get 'edit' => 'users#edit'
    resources :shops do
      resources :items do
        resources :photos
      end
    end
  end
  resources :users
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  attr_accessible :created_at, :name, :description, :user_id, :items

  belongs_to :user
  has_many :items
  has_many :photos, :through => :items

  validates_presence_of :name, :on => :create
  validates_presence_of :description, :on => :create
  validates_uniqueness_of :name, :scope => :user_id
  validates_associated :user, :items
end

app/controllers/shops_controller.rb
class ShopsController < InheritedResources::Base
  respond_to :html, :json

  rescue_from ActiveRecord::RecordNotFound, :with => :shop_not_found

  before_filter :require_user, :only => [:new, :create, :edit, :update, :destroy]
  before_filter :save_referer, :only => [:edit, :destroy, :show]
  before_filter :load_items, :only => [:show]

  after_filter :shop_not_found, :only => [:edit, :destroy, :show]
  after_filter :not_users_shop, :only => [:edit, :destroy]

  protected
    def begin_of_association_chain
      if action_name == "index"
        if params.has_key?(:username)
          @user = User.find_by_username(params[:username])
        end
      elsif action_name == "create" || action_name == "update"
        @user = current_user;
      end
      @user
    end

    def collection
      @shops ||= end_of_association_chain.order(:created_at).page(params[:page]).per(10)
    end

  private
    def save_referer
      session[:return_to] ||= request.referer
      session[:return_to] ||= root_path # If empty, go to root
    end

    def shop_not_found
      unless @shop
        flash[:alert] = "Could not find shop with ID " + params[:id]
        redirect_to session.delete(:return_to)
        return false
      end
    end

    def not_users_shop
      unless @shop.user == current_user
        flash[:alert] = "You are not to owner of this shop. You cannot edit it"
        redirect_to session.delete(:return_to)
        return false
      end
    end

    def load_items
      @items = resource.items.order(:created_at).page(params[:page]).per(5)
    end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= form_for(@shop) do |f| %>
  <% if @shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% @shop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit 'Create Shop', :class => 'btn' %>
  </div>
<% end %>

app/views/shops/_shop.html.erb
<%= div_for shop do %>
  <tr>
    <td><%= link_to shop.name, shop %></td>
    <td><%= shop.description %></td>
    <td>
      <%= link_to shop_path(shop),
                  :rel => 'tooltip',
                  :title => 'Share Shop' do %>
        <i class="icon-share"></i>
      <% end %>
      <% if shop.user == current_user %>
        <%= link_to edit_shop_path(shop),
                    :rel => 'tooltip',
                    :title => 'Edit Shop' do %>
          <i class="icon-edit"></i>
        <% end %>
        <%= link_to shop_path(shop),
                    :confirm => 'Are you sure you want to delete this shop?',
                    :method => :delete,
                    :rel => 'tooltip',
                    :title => 'Delete Shop' do %>
          <i class="icon-remove"></i>
        <% end %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/shops/_shop_list.html.erb
<%= paginate @shops %>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Actions</th>
  </tr>

<%= render @shops %>
</table>

<br />

app/views/shops/edit.html.erb
<% provide(:title, 'Editing shop') %>
<% provide(:page_heading, 'Editing shop') %>

<%= render 'form' %>

<%= link_to 'Show', @shop, :class => 'btn' %> 
<%= link_to 'Back', shops_path, :class => 'btn' %>

app/views/shops/index.html.erb
<% provide(:title, 'Shop List') %>
<% content_for :page_heading do %>
  <% if @user %>
  <%= image_tag(@user.avatar.tiny.url, :class => 'img-polaroid') %> <%= @user.fullname %>'s Shops
  <% else %>
    All Shops
  <% end %>
<% end %>

<%= render 'shop_list' %>

<%= link_to 'New Shop', new_shop_path, :class => 'btn btn-primary' %>

app/views/shops/my_index.html.erb
<% provide(:title, 'My Shops') %>
<% provide(:page_heading, "#{current_user.fullname}'s Shops") %>

<%= render 'shop_list' %>

<%= link_to 'New Shop', new_shop_path, :class => 'btn' %>

app/views/shops/new.html.erb
<% provide(:title, 'New Shop') %>
<% provide(:page_heading, 'Create a new Shop') %>

<%= render 'form' %>

<%= link_to 'Back', shops_path, :class => 'btn' %>

app/views/shops/show.html.erb
<% provide(:title, "Shop Info - #{@shop.name}") %>

<% content_for :page_heading do %>
  <%= @shop.name %>
  <small><%= @shop.user.fullname %></small>
<% end %>

<% content_for :breadcrumbs do %>
  <ul class="breadcrumb">
  <li><%= link_to "OpenMarket", root_path %> <span class="divider">/</span></li>
  <li class="active"><%= @shop.name %></li>
  </ul>
<% end %>

<hr class="featurette-divider">

<div class="row">
  <div class="span2">
    <%= @shop.description %>
  </div><!-- /.span4 -->
  <div class="span10">
    <%= paginate @items %>
    <table class="table table-bordered">
    <tr><th>Name</th><th>Description</th><th>Actions</th></tr>
    <%= render @items %>
    </table>
  </div><!-- /.span8 -->
</div><!-- /.row -->
<%= link_to 'Add item', new_shop_item_path(@shop.id), :class => 'btn btn-primary' %>