config/routes.rb
OpenMarket::Application.routes.draw do
  get "search/simple"

  get "search/advanced"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  #
  # Static pages
  #
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"

  #
  # Default routes
  #
  resources :items do
    resources :photos
  end
  resources :shops do
    resources :items do
      resources :photos
    end
  end
  resources :sessions

  #
  # Root
  #
  root :to => 'static_pages#home'

  #
  # Generic paths
  #
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/signup',  to: 'users#new'
  match '/search',  to: 'search#simple'
  match '/search/advanced',  to: 'search#advanced'
  match '/login',   to: 'sessions#new'
  match '/logout',  to: 'sessions#destroy'

  match '/users/:username/edit', to: 'users#edit'
  match '/users/:username', to: 'users#update', :via => :put
  match '/users/:username', to: redirect { |params, req| "/#{params[:username]}" }

  #
  # Paths for user scoped access
  #
  scope '/:username', :constraints => ProfileConstraint do
    get '' => 'users#show'
    get 'edit' => 'users#edit'
    resources :shops do
      resources :items do
        resources :photos
      end
    end
  end
  resources :users
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :active, :created_at, :description, :name, :price,
                  :quantity, :shop, :shop_id, :user, :user_id,
                  :db_seeding

  has_many :photos

  belongs_to :shop
  belongs_to :user

  validates_uniqueness_of :name, :scope => :shop_id
  validates_associated :shop, :unless => :db_seeding
end

app/controllers/items_controller.rb
class ItemsController < InheritedResources::Base
  respond_to :html, :json

  rescue_from ActiveRecord::RecordNotFound, :with => :item_not_found

  before_filter :require_user, :only => [:new, :create, :edit, :update, :destroy]
  before_filter :save_referer, :only => [:edit, :destroy, :show]
  before_filter :load_photos, :only => [:show, :edit, :update]

  after_filter :item_not_found, :only => [:edit, :destroy, :show, :update]
  after_filter :not_users_item, :only => [:edit, :destroy, :update]

  belongs_to :shop

  protected
    def collection
      @items ||= end_of_association_chain.order(:created_at).page(params[:page]).per(5)
    end

  private
    def save_referer
      session[:return_to] ||= request.referer
      session[:return_to] ||= root_path # If empty, go to root
    end

    def item_not_found
      unless @item
        flash[:alert] = "Could not find item with ID " + params[:id] + " within shop ID " + params[:shop_id]
        redirect_to session.delete(:return_to)
        return false
      end
    end

    def not_users_item
      unless @shop.user == current_user
        flash[:alert] = "You are not to owner of this shop. You cannot edit items within"
        redirect_to session.delete(:return_to)
        return false
      end
    end

    def load_photos
      @photos = resource.photos.order(:created_at).page(params[:page]).per(5)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for([@shop, @item]) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <% @photos.each do |photo| %>
  <div class="field">
    <%= image_tag(photo.image.thumb.url) %>
    <!-- %= link_to 'Delete', shop_item_photo_destory_path(@shop, @item, photo), :class => 'btn' % -->
    <%= link_to item_photo_path(photo.item, photo),
                :confirm => 'Are you sure you want to delete this photo?',
                :method => :delete,
                :rel => 'tooltip',
                :title => 'Delete Photo',
                :class => 'btn' %>
  </div>
  <% end %>
  <div class="actions">
    <%= f.submit 'Create item', :class => 'btn btn-primary' %>
    <%= link_to 'Add a photo', new_shop_item_photo_path(@shop, @item), :class => 'btn' %>
    <%= link_to 'Back', shop_path(@shop), :class => 'btn' %>
  </div>
<% end %>

app/views/items/_item.html.erb
<%= div_for item do %>
  <tr>
    <td><%= link_to item.name, shop_item_path(item.shop, item) %></td>
    <td><%= item.description %></td>
    <td>
      <%= link_to shop_item_path(item.shop, item),
                  :rel => 'tooltip',
                  :title => 'Share Item' do %>
        <i class="icon-share"></i>
      <% end %>
      <% if item.shop.user == current_user %>
        <%= link_to edit_shop_item_path(item.shop, item),
                    :rel => 'tooltip',
                    :title => 'Edit Item' do %>
          <i class="icon-edit"></i>
        <% end %>
        <%= link_to shop_item_path(item.shop, item),
                    :confirm => 'Are you sure you want to delete this item?',
                    :method => :delete,
                    :rel => 'tooltip',
                    :title => 'Delete Item' do %>
          <i class="icon-remove"></i>
        <% end %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/items/_item_list.html.erb
<%= paginate @items %>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Actions</th>
  </tr>

<%= render @items %>
</table>

<br />

app/views/items/edit.html.erb
<% provide(:title, 'Edit Item') %>
<% provide(:page_heading, "Editing #{@item.name}") %>
<% content_for :breadcrumbs do %>
  <ul class="breadcrumb">
  <li><%= link_to "OpenMarket", root_path %> <span class="divider">/</span></li>
  <li><%= link_to "#{@shop.name}", shop_path(@shop) %> <span class="divider">/</span></li>
  <li class="active">Edit item</li>
  </ul>
<% end %>

<%= render 'form' %>

<%= link_to 'Back', shop_item_path(@shop.id, @item.id), :class => 'btn' %>

app/views/items/index.html.erb
<% provide(:title, 'Item List') %>
<% provide(:page_heading, "Items in #{@item.shop.name}") %>

<%= render 'item_list' %>

<%= link_to 'New Item', new_item_path, :class => 'btn' %>

app/views/items/new.html.erb
<% provide(:title, 'New Item') %>
<% provide(:page_heading, "New item for shop #{@shop.name}") %>
<% content_for :breadcrumbs do %>
  <ul class="breadcrumb">
  <li><%= link_to "OpenMarket", root_path %> <span class="divider">/</span></li>
  <li><%= link_to "#{@shop.name}", shop_path(@shop) %> <span class="divider">/</span></li>
  <li class="active">New item</li>
  </ul>
<% end %>

<%= render 'form' %>

<%= link_to 'Back', shop_path(@shop.id), :class => 'btn' %>

app/views/items/show.html.erb
<% provide(:title, "Item - #{@item.shop.name} - #{@item.name}") %>
<% content_for :page_heading do %>
<%= @item.name %>
  <% if @item.active %>
    <span class="label label-success">Active</span>
  <% else %>
    <span class="label">Inactive</span>
  <% end %>
<% end %>

<% content_for :breadcrumbs do %>
  <ul class="breadcrumb">
  <li><%= link_to "OpenMarket", root_path %> <span class="divider">/</span></li>
  <li><%= link_to "#{@item.shop.name}", shop_path(@item.shop) %> <span class="divider">/</span></li>
  <li class="active"><%= @item.name %></li>
  </ul>
<% end %>

<hr class="featurette-divider">

<div class="row">
  <div class="span2">
    <table class="table table-bordered">
    <tr><th>Price</th><td><%= number_to_currency(@item.price, :precision => 2) %></td></tr>
    <tr><th>Quantity</th><td><%= @item.quantity %></td></tr>
    </table>
  </div><!-- /.span4 -->
  <div class="span10">
    <%= @item.description %>
    <%= paginate @photos %>
    <table class="table table-bordered">
    <tr><th>Name</th><th>Description</th><th>Actions</th></tr>
    <%= render @photos %>
    </table>

  </div><!-- /.span8 -->
</div><!-- /.row -->

<% if current_user && current_user.id == @item.shop.user_id %>
<%= link_to 'Add a photo', new_shop_item_photo_path(@shop.id, @item.id), :class => 'btn btn-primary' %>
<%= link_to 'Edit Item', edit_shop_item_path(@item.shop, @item), :class => 'btn btn-primary' %>
<% end %>