config/routes.rb
OpenMarket::Application.routes.draw do
  get "search/simple"

  get "search/advanced"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  #
  # Static pages
  #
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"

  #
  # Default routes
  #
  resources :items do
    resources :photos
  end
  resources :shops do
    resources :items do
      resources :photos
    end
  end
  resources :sessions

  #
  # Root
  #
  root :to => 'static_pages#home'

  #
  # Generic paths
  #
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/signup',  to: 'users#new'
  match '/search',  to: 'search#simple'
  match '/search/advanced',  to: 'search#advanced'
  match '/login',   to: 'sessions#new'
  match '/logout',  to: 'sessions#destroy'

  match '/users/:username/edit', to: 'users#edit'
  match '/users/:username', to: 'users#update', :via => :put
  match '/users/:username', to: redirect { |params, req| "/#{params[:username]}" }

  #
  # Paths for user scoped access
  #
  scope '/:username', :constraints => ProfileConstraint do
    get '' => 'users#show'
    get 'edit' => 'users#edit'
    resources :shops do
      resources :items do
        resources :photos
      end
    end
  end
  resources :users
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :caption, :image, :image_cache, :remove_image

  belongs_to :item

  mount_uploader :image, PhotoUploader

  validates_presence_of :image, :scope => :item_id
  validates_presence_of :caption, :scope => :item_id
end

app/controllers/photos_controller.rb
class PhotosController < InheritedResources::Base
  respond_to :html, :json

  rescue_from ActiveRecord::RecordNotFound, :with => :photo_not_found

  before_filter :require_user, :only => [:new, :create, :edit, :update, :destroy]
  before_filter :save_referer, :only => [:edit, :destroy, :show]

  after_filter :photo_not_found, :only => [:edit, :destroy, :show, :update]

  belongs_to :item

  def index
    redirect_to shop_item_path(params['shop_id'], params['item_id'])
  end

  def create
    create! { shop_item_path(resource.item.shop, resource.item) }
  end

  def destroy
    destroy! { shop_item_path(resource.item.shop, resource.item) }
  end

  protected
    def collection
      @photos ||= end_of_association_chain.order(:created_at).page(params[:page]).per(5)
    end

  private
    def save_referer
      session[:return_to] ||= request.referer
      session[:return_to] ||= root_path # If empty, go to root
    end

    def photo_not_found
      unless @photo
        flash[:alert] = "Could not find photo with ID " + params[:id]
        redirect_to session.delete(:return_to)
        return false
      end
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for([@item, @photo]) do |f| %>
  <% if @photo.errors.any? %>
    <div class="well">
      <b><%= pluralize(@photo.errors.count, "error") %>
        prohibited this user from being saved:</b>
      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li class="text-error"><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <dl class="dl-horizontal">
    <dt><%= f.label :image %></dt>
    <dd>
      <% if action_name == 'edit' %>
        <%= image_tag(@photo.image.thumb.url) %>
        <%= f.hidden_field :image_cache %>
      <% end %>
      <%= f.file_field :image %>
    </dd>
  </dl>

  <dl class="dl-horizontal">
    <dt><%= f.label :caption %></dt>
    <dd><%= f.text_area :caption, :rows => '3', :cols => '50' %></dd>
  </dl>

  <div class="actions">
    <%= f.submit ((action_name == 'edit') ? 'Update photo' : 'Add photo'), :class => 'btn btn-primary' %>
    <%= link_to 'Cancel', shop_item_path(@photo.item.shop, @photo.item), :class => 'btn' %>
  </div>
<% end %>

app/views/photos/_photo.html.erb
<%= div_for photo do %>
  <tr>
    <td><%= link_to item_photo_path(photo.item, photo) do %>
      <%= image_tag(photo.image.thumb.url, :class => 'img-polaroid') %>
    <% end %>
    </td>
    <td><%= photo.caption %></td>
    <td>
      <%= link_to item_photo_path(photo.item, photo),
                  :rel => 'tooltip',
                  :title => 'Share Item' do %>
        <i class="icon-share"></i>
      <% end %>
      <% if photo.item.shop.user == current_user %>
        <%= link_to edit_item_photo_path(photo.item, photo),
                    :rel => 'tooltip',
                    :title => 'Edit Photo' do %>
          <i class="icon-edit"></i>
        <% end %>
        <%= link_to item_photo_path(photo.item, photo),
                    :confirm => 'Are you sure you want to delete this photo?',
                    :method => :delete,
                    :rel => 'tooltip',
                    :title => 'Delete Photo' do %>
          <i class="icon-remove"></i>
        <% end %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/photos/edit.html.erb
<% provide(:title, 'Edit Photo') %>
<% provide(:page_heading, "Editing Photo") %>
<% content_for :breadcrumbs do %>
  <ul class="breadcrumb">
  <li><%= link_to "OpenMarket", root_path %> <span class="divider">/</span></li>
  <li><%= link_to "#{@photo.item.shop.name}", shop_path(@photo.item.shop) %> <span class="divider">/</span></li>
  <li><%= link_to "#{@photo.item.name}", shop_item_path(@photo.item.shop, @photo.item) %> <span class="divider">/</span></li>
  <li class="active">Edit photo</li>
  </ul>
<% end %>

<%= render 'form' %>

<%= link_to 'Back', shop_item_path(@item.shop, @item) %>

app/views/photos/new.html.erb
<% provide(:title, "New photo for #{@photo.item.shop.name} / #{@photo.item.name}") %>
<% content_for :page_heading do %>
  New photo for <%= @photo.item.name %>
<% end %>

<% content_for :breadcrumbs do %>
  <ul class="breadcrumb">
  <li><%= link_to "OpenMarket", root_path %> <span class="divider">/</span></li>
  <li><%= link_to "#{@photo.item.shop.name}", shop_path(@photo.item.shop) %> <span class="divider">/</span></li>
  <li><%= link_to "#{@photo.item.name}", shop_item_path(@photo.item.shop, @photo.item) %> <span class="divider">/</span></li>
  <li class="active">New photo</li>
  </ul>
<% end %>

<hr class="featurette-divider">

<%= render 'form' %>

app/views/photos/show.html.erb
<% provide(:title, "Photo - #{@photo.item.shop.name} - #{@photo.item.name}") %>
<% content_for :page_heading do %>
  Photo for <%= @photo.item.name %>
<% end %>

<% content_for :breadcrumbs do %>
  <ul class="breadcrumb">
  <li><%= link_to "OpenMarket", root_path %> <span class="divider">/</span></li>
  <li><%= link_to "#{@photo.item.shop.name}", shop_path(@photo.item.shop) %> <span class="divider">/</span></li>
  <li><%= link_to "#{@photo.item.name}", shop_item_path(@photo.item.shop, @photo.item) %> <span class="divider">/</span></li>
  <li class="active">Item photo</li>
  </ul>
<% end %>

<hr class="featurette-divider">

<%= image_tag(@photo.image.url, :class => 'img-polaroid') %>
<%= image_tag(@photo.image.thumb.url, :class => 'img-polaroid') %>

<%= link_to 'Edit', edit_shop_item_photo_path(@item.shop, @item, @photo) %> |
<%= link_to 'All photos', shop_item_photos_path(@item.shop, @item) %> |
<%= link_to 'Back to Item', shop_item_path(@item.shop, @item) %>